<h2 class="subheading">Freelancers and clients deserve ways to connect online</h2>
<p>One of the most beautiful aspects of the internet is the way it allows people to meet those they otherwise wouldn’t. This can include freelancers and clients. When brought together, they both benefit. The freelancer is able to earn money from their skills and the client gets to find someone who knows how to do the thing they need to have done. Should be simple, right?</p>
<h2 class="subheading">But shady corporations seek to profit from connection</h2>
<p>Fiverr, one of the largest freelance platforms, takes a 20% cut of freelancer earnings. Surely they spend that money in ways that make life better for their users, right? Nope! They promote generative AI as an alternative to human freelancers. They invest in weird ad campaigns that seek to normalize unhealthy hustle culture. And that’s not even the worst of it.</p>
<p>Fiverr is an Israeli company whose CEO has stated he chose to incorporate in Israel <a href="https://www.calcalistech.com/ctechnews/article/r1f14fkbn#google_vignette" target="_blank">“for Zionist reasons,”</a> because he wants the company's taxes to go to Israel. In fact, he discusses the need to balance his loyalty to Israel with his loyalty to shareholders. But where is his concern for the humans who rely on his platform, the humans his country is committing a genocide against, and the planet that all known life forms need to share?</p>
<p>A well-known alternative to Fiverr is Upwork, which allows clients to post jobs that freelancers can bid on. Bidding requires “connect” tokens, and while freelancers get some free tokens each month, many end up having to purchase additional tokens just to find work. And once they do land a job, freelancers can expect Upwork to take a 10% cut. </p>
<p>Upwork claims it employs a fraud prevention team to protect users from scams. But after a <a href="https://www.upwork.com/press/releases/upwork-ceo-hayden-brown-shared-the-following-message-with-employees-on-may-7-2026" target="_blank">series of layoffs,</a> both freelancers and clients report that <a href="https://mashable.com/article/upwork-scam-safety" target="_href">scammers are running rampant.</a> In fact, some point out that the company has an incentive to keep as many scammers as possible on the site. More users–legitimate or not–means more connect tokens being spent, which means more money being spent. This is sad, but not surprising, when you consider that as a capitalist corporation, Upwork will always prioritize the happiness of its shareholders (including <a href="https://finance.yahoo.com/quote/UPWK/holders/" target="_blank">Blackrock, Vanguard, and State Street</a>) over the wellbeing of people and the planet.</p>
<p>Luckily, you don’t need capitalism to run a company.</p>
<h2 class="subheading">Cooperative ownership offers a better way</h2>
<p>With a co-op, freelancers and clients will be able to take better care of themselves and each other. They’ll get to keep more of their own money. They’ll run the company democratically, which means they will get to participate in making decisions, such as:</p>
<ul>
    <li>How to handle allegations of scamming</li>
    <li>Whether to ban generative AI from being used in all services offered on the platform</li>
    <li>How much of the company budget should go towards advertising</li>
    <li>and more</li>
</ul>
<p>And as Care for Community is one the Cooperative Principles, a worldwide networking platform that’s cooperatively owned will be better for the whole world, too. After all, most people aren’t evil. Most people don’t have the desire to siphon as much money as they can from hardworking folks and feed it to a genocidal government. Most people don’t want to become millionaire CEOs just so they wake up one day and fire a quarter of the workers who helped them become rich. The majority of people simply want to live happy, comfortable lives doing what they love, and they want the same for others, too. That’s why we should put the majority of people in charge.</p>